config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  authenticate :user, lambda { |user| user.is_a?(Admin) } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root 'redirect#index'

  scope module: 'admins' do
    resources :admins, only: :show

    resources :articles, except: %i[index show] do
      member do
        post 'activate'
      end
    end

    resources :article_uploads do
      collection do
        post 'upload'
      end
    end
  end

  scope module: 'readers' do
    resources :readers, only: :show
    resources :articles, only: %i[index show] do
      collection do
        get 'search'
      end
    end
  end
end

app/models/article_upload.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: article_uploads
#
#  id            :bigint           not null, primary key
#  attachment    :string
#  upload_errors :text             default([]), is an Array
#  article_id    :bigint
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
class ArticleUpload < ApplicationRecord
  belongs_to :article, optional: true

  mount_uploader :attachment, FileUploader
end

app/controllers/admins/article_uploads_controller.rb
# frozen_string_literal: true

module Admins
  class ArticleUploadsController < ApplicationController
    def new
      @article_upload = ArticleUpload.new

      authorize @article_upload
    end

    def upload
      authorize current_user, policy_class: ArticleUploadPolicy

      ArticleUploadService.call(params[:attachment], current_user)

      redirect_to root_path
    end
  end
end

app/controllers/article_uploads_controller.rb
# frozen_string_literal: true

class ArticleUploadsController < ApplicationController
  def new
    @article_upload = ArticleUpload.new
  end

  def upload
    ArticleUploadService.call(params[:attachment], current_user)

    redirect_to root_path
  end
end

app/views/admins/article_uploads/new.html.erb
<%= form_for @article_upload, url: upload_article_uploads_path, method: "post", html: { multipart: true } do |f| %>
  <div class="attachment-container">
    <div class="attachment-item">
    </div>
  </div>

  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

<br>
<button class="add-article btn btn-primary">Add one more article</button>

<script>
  const addArticleBtn = document.getElementsByClassName("add-article")[0];
  const attachmentContainer = document.getElementsByClassName("attachment-container")[0];

  const addArticle = () => {
    const itemContainer = document.createElement('div');
    const itemLabel = document.createElement('label');
    const itemUploader = document.createElement('input');
    const index = attachmentContainer.getElementsByClassName('attachment-item').length - 1;

    itemContainer.classList.add('attachment-item');
    itemLabel.textContent = 'Attachment: ';
    itemUploader.setAttribute("type", "file");
    itemUploader.id = `attachment_${index}`;
    itemUploader.name = `attachment[${index}]`;

    itemContainer.appendChild(itemLabel);
    itemContainer.appendChild(itemUploader);

    attachmentContainer.appendChild(itemContainer)
  };

  addArticleBtn.addEventListener('click', addArticle);
</script>