config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  authenticate :user, lambda { |user| user.is_a?(Admin) } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root 'redirect#index'

  scope module: 'admins' do
    resources :admins, only: :show

    resources :articles, except: %i[index show] do
      member do
        post 'activate'
      end
    end

    resources :article_uploads do
      collection do
        post 'upload'
      end
    end
  end

  scope module: 'readers' do
    resources :readers, only: :show
    resources :articles, only: %i[index show] do
      collection do
        get 'search'
      end
    end
  end
end

app/views/admins/admins/_article_row.html.erb
<tr>
  <td scope="row"><%= article.id %></td>
  <td><%= article.category || 'No Category' %></td>
  <td><%= article.status %></td>
  <td><%= article.tags.pluck(:name).join(',') %></td>
  <td>
    <%= link_to 'Edit', edit_article_path(article.id)%>
    <%= link_to 'Delete', article_path(article.id), data: { method: :delete }%>
    <%= link_to 'Activate', activate_article_path(article.id), data: { method: :post } unless article.active? %>
  </td>
  <td colspan="2"><%= article.content %></td>
</tr>

app/views/admins/admins/_articles_table.html.erb
<table class="table" id="articles_table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Category</th>
      <th scope="col">Status</th>
      <th scope="col">Tags</th>
      <th scope="col">Links</th>
      <th scope="col">Content</th>
      <th scope="col" style="text-align: right">Articles count <%= Article.count %></th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: "article_row", collection: Article.all.order(id: :desc), as: :article %>
  </tbody>
</table>

app/views/admins/admins/show.html.erb
<%= link_to "Batch upload", new_article_upload_path, class: "btn btn-light" %>
<%= link_to "New Article", new_article_path, class: "btn btn-light" %>
<%= render partial: "articles_table" %>