config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  authenticate :user, lambda { |user| user.is_a?(Admin) } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root 'redirect#index'

  scope module: 'admins' do
    resources :admins, only: :show

    resources :articles, except: %i[index show] do
      member do
        post 'activate'
      end
    end

    resources :article_uploads do
      collection do
        post 'upload'
      end
    end
  end

  scope module: 'readers' do
    resources :readers, only: :show
    resources :articles, only: %i[index show] do
      collection do
        get 'search'
      end
    end
  end
end

app/models/article.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: articles
#
#  id           :bigint           not null, primary key
#  category     :string
#  tsv_category :tsvector
#  status       :string           default("draft"), not null
#  user_id      :bigint           not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Article < ApplicationRecord
  include AASM
  include ElasticSearchable

  has_rich_text :content

  belongs_to :admin, foreign_key: 'user_id', inverse_of: :articles

  has_one :article_upload, dependent: :destroy
  has_many :article_tags, dependent: :destroy
  has_many :tags, through: :article_tags

  # DOC:
  # Lifecycle for 1 article:
  # draft -> active
  # Lifecycle for 2 or more articles:
  # draft -> in_process -> active
  # draft -> in_process -> failed -> in_process -> active
  # rubocop:disable Metrics/BlockLength
  aasm column: :status do
    state :draft, initial: true
    state :in_process
    state :failed
    state :active
    state :inactive

    event :in_process do
      transitions from: %i[draft failed], to: :in_process
    end

    event :fail do
      transitions from: :in_process, to: :failed
    end

    event :activate do
      transitions from: %i[draft in_process failed inactive], to: :active
    end

    event :inactivate do
      transitions from: %i[draft active], to: :inactive
    end
  end
  # rubocop:enable Metrics/BlockLength
end

app/models/reader.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  type                   :string           not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string
#
class Reader < User
end

app/controllers/admins/articles_controller.rb
# frozen_string_literal: true

module Admins
  class ArticlesController < ApplicationController
    before_action :set_article, only: %i[edit update destroy activate]

    def new
      @form = Articles::BaseForm.new({}, current_user)

      authorize @form
    end

    def create
      @form = Articles::CreateForm.new(articles_params, current_user)

      authorize @form, policy_class: Articles::BaseFormPolicy

      if @form.save
        redirect_to root_path, notice: 'New Article is created'
      else
        render :new
      end
    end

    def edit
      @form = Articles::BaseForm.new({}, current_user)

      authorize @form
    end

    def update
      @form = Articles::UpdateForm.new(articles_params, current_user, @article)

      if @form.save
        redirect_to root_path, notice: 'Article is updated'
      else
        render :edit
      end
    end

    def destroy
      if @article.destroy!
        redirect_to root_path, notice: 'Article is deleted'
      else
        flash[:notice] = @article.errors
      end
    end

    def activate
      if @article.activate!
        redirect_to root_path, notice: 'Article is activated'
      else
        flash[:notice] = @article.errors
      end
    end

    private

    def set_article
      @article = Article.find(params[:id])

      authorize @article
    end

    def articles_params
      params.require(:articles_form).permit(:content, :category, article_tags: [tag_ids: []])
    end
  end
end

app/controllers/readers/articles_controller.rb
# frozen_string_literal: true

module Readers
  class ArticlesController < ApplicationController
    def index
      @articles_searches = ArticlesSearch.tsv_articles_search(params[:query])

      authorize @articles_searches
    end

    def search
      @articles_searches = Article.search(params[:query]).results

      authorize @articles_searches, policy_class: ArticlesSearchPolicy
    end

    def show
      @articles_search = ArticlesSearch.find(params[:id])

      authorize @articles_search
    end
  end
end

app/controllers/readers/readers_controller.rb
# frozen_string_literal: true

module Readers
  class ReadersController < ApplicationController
    def show
      authorize current_user, policy_class: ReaderPolicy
    end
  end
end

app/views/readers/articles/_article_row.html.erb
<tr>
  <th scope="row"><%= article.id %></th>
  <td><%= article.category %></td>
  <td><%= article.tags.pluck(:name).join(', ') %></td>
  <td>
    <%= link_to 'View', article_path(article.id)%>
  </td>
  <td colspan="2"><%= truncate(article.content.body, length: 100, escape: false).html_safe %></td>
</tr>

app/views/readers/articles/_articles_table.html.erb
<table class="table" id="articles_table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Category</th>
      <th scope="col">Tag</th>
      <th scope="col">Links</th>
      <th scope="col">Content</th>
      <th scope="col" style="text-align: right">Articles count <%= @articles_searches.count %></th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: "article_row", collection: @articles_searches, as: :article %>
  </tbody>
</table>

app/views/readers/articles/index.html.erb
<%= form_with url: articles_path, method: :get, local: true do |form| %>
  <div class="input-group mb-3">
    <%= form.text_field :query, class: "form-control", placeholder: 'Fill in...' %>
    <div class="input-group-append">
      <%= form.submit "Search", class: "btn btn-outline-secondary"%>
    </div>
  </div>
<% end %>

<%= render partial: "articles_table", articles_searches: @articles_searches %>

app/views/readers/articles/search.html.erb
<%= form_with url: search_articles_path, method: :get, local: true do |form| %>
  <div class="input-group mb-3">
    <%= form.text_field :query, class: "form-control", placeholder: 'Fill in...' %>
    <div class="input-group-append">
      <%= form.submit "Search", class: "btn btn-outline-secondary"%>
    </div>
  </div>
<% end %>

<%= render partial: "articles_table", articles_searches: @articles_searches %>

app/views/readers/articles/show.html.erb
<%= @articles_search.term.html_safe %>